sudo: false

language: node_js

node_js:
  - 10.15.3

install:
  - npm ci
  
script:
 - npm run test:elint
 
 notifications:
  webhooks: https://ptb.discordapp.com/api/webhooks/759436309470773258/WOixQkiFKMxLqDH7PksVIDuPbfCXs8jYMjYg30DzPtmVB5iON_BPMPD97Tx--b8OBPZN
